# Generated by Django 3.2.9 on 2022-01-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220124_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_name',
        ),
    ]
